### ISSUE TITLE
Update Application to allow marks to be uploaded

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/wine-price-api#16]
Via the admin interface, an admin is able to select marks to be updated to the wine-price database.  These marks remain persistent, and are identified on the pages with a special color, identifying that the mark is completed.

Marks have schema:

``` sql
CREATE TABLE marks (
   mark_id uuid primary key,
   user_id uuid,
   page_id uuid,
   xy integer[2],
   type text references mark_type (type),
   wineType text references wine_type(wineType),
   color text references wine_color(color),
   country text,
   producer text,
   section text,
   vintage integer,
   bottletype text,
   perPrice double precision,
   casePrice double precision,
   created timestamp without time zone,
   updated timestamp without time zone
)
```

**Comment by qjhart** [comment]
Two additional roles have been created, 'markup' and 'admin'.  Only the 'markup' role has been fleshed out.  This is so a user can mistakenly delete catalogs or pages.  Right now 'admins' only have the same roles as 'markup', That is you can't modify catalogs or pages from the API, only marks and pending_mark_index.

Any user can download marks.

**Comment by qjhart** [comment]
@jrmerz please note that while GETs to the marks work okay, POSTs to the mark require that the format of the xy array is in postgresql format, so you POST like this: 

``` json
{ 
	"mark_id":"d9dc8dc7-25fe-4573-b177-4b070a93314c",
	"user_id":null,
	"page_id":"53d26bb7-8b10-47d6-89da-34883c0cc324",
	"xy":"{34,113}",
	"type":"wine",
	"winetype":"Still",
	"color":"Red",
	"country":"USA",
	"producer":"Foo",
	"section":"Foo Wines",
	"vintage":1956,
	"bottletype":"Standard",
	"perprice":3.30,
	"caseprice":33.00,
	"created":"2017-03-30T23:13:10.757999",
	"updated":"2017-03-30T23:13:10.757999"
}
```

**Comment by jrmerz** [comment]
@qjhart schema looks good, only thing is I had a flag for if the user is anonymous.  Did you want to keep this flag or drop it?

Also, I don't follow the roles description provided above.

**Comment by jrmerz** [comment]
@qjhart FYI, I pushed schema changes: https://github.com/UCDavisLibrary/wine-price-api/commit/6082a4ff0941b42619fa957b7b342fc04cac4a12

Marks can now be approved, though this shed light on a new issue https://github.com/UCDavisLibrary/wine-price-api/issues/17
