### ISSUE TITLE
Page result should include mark count

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/wine-price-api#17]
A page result should include the number of marks approved (number of marks in the mark table with same page_id).  Not sure if you write a view, trigger or other for this.

Currently this count is stored in Firebase, but that is really the number of pending marks, something I think we can ditch.  When a mark is approved, the mark is removed from Firebase, so this Firebase count actually goes down.

**Comment by qjhart** [comment]
``` bash
http GET http://api.catalogs.qjhart.org/pages select==page_id,page,marks marks==gt.0
```

This example shows how you can get the number of marks on a page, or find all the pages that have marks on them. page.marks is a function, and as such, it does NOT appear in the default output. It must be selected explicitly
