### ISSUE TITLE
Define catalog functions to determine if pages are all complete.

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/wine-price-api#18]
can you add two views to catalogs.  total number of approved marks and total number of completed pages?  A completed page can be either set to editable=false or ignore=true.  Finally, we can then have a completed catalog be if completed pages count == pages count?

**Comment by qjhart** [comment]
@jrmerz 

There are two options here:

## Three new functions

Add:
catalog.pages 
catalog.pages_finished
catalog.pages_not_finished = editable pages not complete. (=0 then complete)

``` bash
http http://api.catalogs.qjhart.org/catalogs select==catalog_id,pages,pages_finished,pages_not_finished
```
``` json
[
    {
        "catalog_id": "a60bb267-fe06-4fae-81db-4da9518b95ab", 
        "pages": 17, 
        "pages_finished": 1, 
        "pages_not_finished": 16
    }, 
    {
        "catalog_id": "b2408313-b588-413d-9fef-af19268eb53b", 
        "pages": 8, 
        "pages_finished": 1, 
        "pages_not_finished": 7
    }
]
```
## One new function

Alternatively: If we know we will always need all three, it's probably better to use a composite type as in:
page_count: { "total":44, finished:20}, sine it should run faster.  As in:

``` bash
http http://api.catalogs.qjhart.org/catalogs select==catalog_id,pages,page_count limit=1
```
``` json
[
    {
        "catalog_id": "a60bb267-fe06-4fae-81db-4da9518b95ab", 
        "page_count": {
            "finished": 1, 
            "not_finished": 16, 
            "total": 17
        }
    }, 
    {
        "catalog_id": "b2408313-b588-413d-9fef-af19268eb53b", 
        "page_count": {
            "finished": 1, 
            "not_finished": 7, 
            "total": 8
        }
    }
]
```

**Comment by jrmerz** [comment]
@qjhart both look good to me, and I'm ok with either response type... I will leave it to you :)

Though if I have page count and finished count, I can always calculate not complete.
