### ISSUE TITLE
Wine Price Browser

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/wine-price-api#4]
Developer a single page web application that allows users to search the wine price data.

**Comment by pablodefendini** [comment]
We can use [this prototype](https://invis.io/T89R5Y4CV#/211430469_Inital) as a starting point for this tool. It will be simpler than what's currently in the prototype, since we will be working with a smaller set of facets.

**Comment by qjhart** [comment]
Moved to wine-label-app
