### ISSUE TITLE
Build UI for price browser

### ISSUE THREAD

**Issue by pablodefendini** [UCDavisLibrary/wine-price-api#5]
Use [this prototype](https://invis.io/T89R5Y4CV#/211430469_Inital)  as the starting point for the design for an interface for the Wine Price Browser tool. 

This is part of the Wine Label App site.

**Comment by pablodefendini** [comment]
For this new iteration, we'll probably want to just do it in HTML and CSS,  as part of this repository.

**Comment by qjhart** [comment]
Moved to wine-label-app
